project_id = "bgvzucvjtikfrviguajx"

[functions.clinic-chat]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false

[functions.send-push]
verify_jwt = false
